### PR TITLE
Add support for the non-standard ALIAS record

### PR DESCRIPTION
**Pull request by DonnchaC**
I am using a DNS provider which supports create non-standard ALIAS records and would like to be able to generate and parse them with your library. I see that you already support the non-standard URL record.

Do you have any problems with adding this record to your library?

### CODE REVIEW

**Comment by jcnelson** [comment]
I don't think it's a problem; will confirm with @shea256 and @muneeb-ali.  Thank you for sending us the PR!

**Comment by shea256** [comment]
👍

**Comment by jcnelson** [comment]
Merged to `rc-0.14.0`.  Will be included in the next `master`!

**Comment by DonnchaC** [comment]
@jcnelson it doesn't look like this is included in 0.14.1. Do you plan to have another release in the near future?

**Comment by jcnelson** [comment]
Whoops, sorry about that.  Merged.

**Pull request merged**
