### PR TITLE
Fix bug where the CLASS was not include in generated zones

### PR DESCRIPTION
**Pull request by DonnchaC**
Somehow `make_zone_file` has been creating RR's without a CLASS field. These zone files are invalid and would not work when I tried to deploy them. 

I've included a fix and a tests for this bug. I also fixed another bug in the excepted result for a URI record test.

### CODE REVIEW

**Comment by jcnelson** [comment]
I think we can merge this :)  But just for my own edification, I was under the impression from RFC 1035 (section 5.1) that `CLASS` was an optional field that, if absent, defaulted to `IN`.  Would be happy to learn otherwise!  Related, do you foresee a need to use `CH` or any of the other classes defined in the RFC?

**Comment by DonnchaC** [comment]
I wasn't aware that CLASS was an optional field. I made this change as my DNS provider could not parse zone fields without the CLASS field. I think it will be more reliable and to always include the field at the cost of a few bytes in the zone file.

**Comment by jcnelson** [comment]
I agree that all other things being equal, it would be best to be explicit on the `CLASS` field for the reason you stated.

There are a couple extra things we'll need to address before merging, though.  Blockstack maps names to the hashes of their zonefiles in the blockchain, but the hash of each zonefile is calculated from its textual representation (i.e. its RFC 1035 representation).  Because `CLASS` was ignored, the zonefile validation logic must grandfather in all the existing zonefiles that lack an explicit `CLASS` so when parsed and re-serialized, the resulting RFC 1035 representation will be the same.

I think the following might solve this:
- If a `CLASS` field is not found in the RFC 1035 representation, the `parse_zone_file` method would include the `CLASS` value `IN` in the resulting RR, as well as a hint that the `CLASS` was implicit.
- The `make_zone_file` method would check each RR for the "missing-`CLASS`" hint when serializing, and exclude the `CLASS` column if the hint is present regardless of whether or not a `CLASS` value is given (so as to recover the original RFC 1035 representation).
- If the hint is not present, `make_zone_file` will require a `CLASS` field for each RR and raise an exception if not given.  This will ensure all new zonefiles have a `CLASS` for each RR.

**Comment by DonnchaC** [comment]
@jcnelson I've implemented the approach you described. Zone files without a CLASS field should have the same RFC 1035 representation when parsed and regenerated.

I think forcing users to specify a CLASS for each record when calling `make_zone_file` leads to a lot of needless overhead. The vast majority of users will just want the "IN" class. Should we use "IN" as the default unless another class is specified?

**Comment by DonnchaC** [comment]
Hi @jcnelson, Do you need anything more from me to merge this?

**Comment by jcnelson** [comment]
Hi @DonnchaC, apologies for not responding to your earlier comment (lost track of time getting ready for the next release).  Your PR looks good :)  We'll merge it for 0.14.  Our release process is BSD-like--we'll release the new server, new CLI, new core libraries (including this one), and new test framework all in one go.

**Comment by DonnchaC** [comment]
Great @jcnelson. I'm just wondering in you have an opinion on not making class a required record parameter for `make_zone_file`:

> I think forcing users to specify a CLASS for each record when calling make_zone_file leads to a lot of needless overhead. The vast majority of users will just want the "IN" class. Should we use "IN" as the default unless another class is specified?

**Comment by jcnelson** [comment]
> The vast majority of users will just want the "IN" class. Should we use "IN" as the default unless another class is specified?

Yes, this sounds like the most sensible option :)

**Comment by DonnchaC** [comment]
@jcnelson cool, I've pushed a commit to default to "IN"

**Comment by jcnelson** [comment]
Merged to `rc-0.14.0`.  Will be included in the next `master`.

**Comment by DonnchaC** [comment]
@jcnelson  Great, thanks for merging this!

**Comment by DonnchaC** [comment]
This has been merged and released. Closing.

**Pull request closed without merging**
